name: Release
on:
  release:
    types: [released]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: thepwagner/action-update-go@main
        with:
          log_level: debug
          dispatch_on_release: |
            thepwagner/action-update-go
            thepwagner/action-update-docker
            thepwagner/action-update-dockerurl
